### ISSUE TITLE
Generated code is not compatible with analyzer strong mode: implicit-casts: false

### ISSUE THREAD

**Issue by slavap** [localizely/flutter-intl-vscode#26]
```yaml
analyzer:
  exclude: [build/**]
  strong-mode:
    implicit-casts: false
```

```dart
class MessageLookup extends MessageLookupByLibrary {
  String get localeName => 'en';

  final messages = _notInlinedMessages(_notInlinedMessages);
  static _notInlinedMessages(_) => <String, Function>{ // <<< must be Map<String, dynamic>_notInlinedMessages
        "aaa": MessageLookupByLibrary.simpleMessage("Aaa"),
```
