### ISSUE TITLE
can't use with implicit-casts: false and implicit-dynamic: false

### ISSUE THREAD

**Issue by basketball-ico** [localizely/flutter-intl-vscode#74]
![image](https://user-images.githubusercontent.com/48268866/124060462-b8c28180-d9f2-11eb-9237-521ddb8ef5c7.png)
```yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
```
```
Missing type arguments for generic type 'Future<dynamic>'.
Try adding an explicit type, or remove implicit-dynamic from your analysis options file.
```

for solve this you only need to add dynamic to all generated code when is implicit

at the moment i only see this 2 cases, but maybe there are more

```dart
  static Map<String, Function> _notInlinedMessages(_) => <String, Function>{};
```

to
```dart
  static Map<String, Function> _notInlinedMessages(dynamic _) => <String, Function>{};
```
and 

```dart
Map<String, LibraryLoader> _deferredLibraries = {
  'en': () => new Future.value(null),
};
```
to
```dart
Map<String, LibraryLoader> _deferredLibraries = {
  'en': () => new Future<dynamic>.value(null),
};
```

**Comment by lzoran** [comment]
Hi @basketball-ico,

Thanks for reporting this!

It is not easy to generate code that will suit any analyzer/linter config.
The `analysis_options.yaml` file contains the `exclude` section, which excludes files and directories from the analysis.
Does updating analyzer config work for you?

The `analysis_options.yaml` file:
```
include: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - lib/generated/l10n.dart
    - lib/generated/intl/*.dart
```

**Please note that earlier were some issues with the `exclude` section of the analyzer. It seems that everything works now with the latest Flutter version (`Flutter 2.2.3`) and the latest IDE plugin/extension for Flutter and Dart.*
