### ISSUE TITLE
Could not find a file named "pubspec.yaml" in "C:\Users\xx\AppData\Local\Pub\Cache\intl_utils-1.9.0".

### ISSUE THREAD

**Issue by jianboy** [localizely/flutter-intl-vscode#78]
Could not find a file named "pubspec.yaml" in "C:\Users\xx\AppData\Local\Pub\Cache\intl_utils-1.9.0".

**Comment by jianboy** [comment]
```
Because intl_utils ^1.9.0 depends on intl_translation 0.17.10+1 which depends on intl >=0.15.3 <0.17.0, intl_utils ^1.9.0 requires intl >=0.15.3 <0.17.0.     
So, because flutter_2048 depends on both intl ^0.17.0 and intl_utils 1.9.0, version solving failed.
pub get failed (1; So, because flutter_2048 depends on both intl ^0.17.0 and intl_utils 1.9.0, version solving failed.)
```


```
name: flutter_xx
description: xx
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations: 
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true

```
