### ISSUE TITLE
dart_style 2.2.0 is not recognized by flutter_intl in VS Code

### ISSUE THREAD

**Issue by ajyong** [localizely/flutter-intl-vscode#82]
EDIT: `flutter pub cache clean` solved the issue.

# Repro Steps

1. I configured `flutter_intl` in my `pubspec.yaml` beforehand because I wanted to deviate from the default behaviour slightly by nesting the `generated/` folder under my `lib/l10n` folder.
1. I followed the [Getting started](https://marketplace.visualstudio.com/items?itemName=localizely.flutter-intl&ssr=false#overview) instructions and tried to execute **Flutter Intl: Initialize**.

# Expected

A generated `intl_en.arb` and `generated` folders as described in the instructions.

# Actual

I get this in the **Output > Flutter Intl** tab of VS Code:

```
INFO: Generating localization files for the 'AMAMobile' project...
Could not find a file named "pubspec.yaml" in "C:\sdks\flutter\.pub-cache\hosted\pub.dartlang.org\dart_style-2.1.1".
pub finished with exit code 66
exit code 66
```

The first thing I tried was bumping the minimum `enviroment:sdk` to `2.14.0`, but that didn't do anything.  That's when I noticed my `pubspec.lock` file locked `dart_style` to `2.2.0`.

My **workaround** is to pin the `dart_style` version under `dev_dependencies` to `2.1.1`.  After doing so and restarting VS Code, the extension started working and generating files as configured.  Ideally, I would like to not have to pin versions going forward.

# Metadata

pubspec.yaml:
```
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_appauth: ^1.1.0+1
  flutter_dotenv: ^5.0.2
  flutter_secure_storage: ^4.2.1
  google_maps_flutter: ^2.0.10
  http: ^0.13.3
  intl: ^0.17.0
  provider: ^6.0.0
  vrouter: ^1.2.0+13
  webview_flutter: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - .env

flutter_intl:
  enabled: true
  class_name: Strings
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/l10n/generated
```

flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.19043.1288], locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.61.0)
[✓] Connected device (2 available)
```
