### ISSUE TITLE
Make paths for "generated" and "l10n" folders configurable

### ISSUE THREAD

**Issue by LeviHassel** [localizely/flutter-intl-vscode#9]
It would be awesome if this extension allowed configurable paths and names for the `generated` and `l10n` folders. This would allow users to organize these folders within their existing file hierarchy. I think this would be most helpful placed alongside the other configuration options in `pubspec.yaml`.

For example, you could have:
```
flutter_intl:
  enabled: true
  l10n_path: lib/data/i18n/localizations
  generated_path: lib/data/i18n/generated
```
