### ISSUE TITLE
Flutter Intl: Upload or Download fails 

### ISSUE THREAD

**Issue by adiospace** [localizely/flutter-intl-vscode#93]
My configuration:

```
flutter_intl:
  enabled: true
  localizely:
    project_id: xxxxxxxx
    download_empty_as: main
```

If i manually upload or download using the `flutter pub run intl_utils:localizely_upload_main` and `flutter pub run intl_utils:localizely_download` everything works as expected but when I do it trough the `Flutter Intl: Upload main ARB file` and `Flutter Intl: Download ARB files` commands in VSCode it fails with `"Failed to download ARB files from Localizely"`. 

I have vscode 1.67.2 and flutter intl 1.18.2 installed.

Is there a way to know why it fails? 

**EDIT** this happens to an existing configured project which worked till now...
